version: '3.8'

services:
  apache:
    build: './apache'
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      frontend:
      backend:
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
      - ./certs:/usr/local/apache2/cert/
    depends_on:
      - php
      - mysql
  php:
    build: './php'
    restart: always
    networks:
      backend:
        ipv4_address: 10.5.0.2
    volumes:
      - ./public_html:/var/www/html
      - ./tmp:/usr/local/tmp
  mysql:
    user: root
    build: './mysql'
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 10.5.0.3

  python:
    build: './python'
    tty: true
    restart: always
    volumes:
      - ./python/logs:/home/ubuntu/logs
      - ./python/home:/home/ubuntu/scripts
    networks:
      backend:
        ipv4_address: 10.5.0.4

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  frontend:
    ipam:
      config:
        - subnet: 10.4.0.0/16
          gateway: 10.4.0.1
